//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fructika.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fructika.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food group images from the following users via Unsplash.
        /// </summary>
        internal static string About_FoodGroupThanks {
            get {
                return ResourceManager.GetString("About_FoodGroupThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;d love to hear how Fructika is working for you..
        /// </summary>
        internal static string About_HowIsFructika {
            get {
                return ResourceManager.GetString("About_HowIsFructika", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon Watermelon from Creative Stall via Noun Project.
        /// </summary>
        internal static string About_IconThanks {
            get {
                return ResourceManager.GetString("About_IconThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;ve got any feedback, you&apos;ve found a bug or you want to suggest a feature please Tweet us:.
        /// </summary>
        internal static string About_SendFeedback {
            get {
                return ResourceManager.GetString("About_SendFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks.
        /// </summary>
        internal static string About_Thanks {
            get {
                return ResourceManager.GetString("About_Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string About_Title {
            get {
                return ResourceManager.GetString("About_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fructose.
        /// </summary>
        internal static string FoodDetail_Fructose {
            get {
                return ResourceManager.GetString("FoodDetail_Fructose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fructose/Glucose Balance.
        /// </summary>
        internal static string FoodDetail_FructoseGlucoseBalance {
            get {
                return ResourceManager.GetString("FoodDetail_FructoseGlucoseBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        internal static string FoodDetail_Glucose {
            get {
                return ResourceManager.GetString("FoodDetail_Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maltose.
        /// </summary>
        internal static string FoodDetail_Maltose {
            get {
                return ResourceManager.GetString("FoodDetail_Maltose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucrose.
        /// </summary>
        internal static string FoodDetail_Sucrose {
            get {
                return ResourceManager.GetString("FoodDetail_Sucrose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sugars per 100g.
        /// </summary>
        internal static string FoodDetail_SugarsPer100 {
            get {
                return ResourceManager.GetString("FoodDetail_SugarsPer100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sugars.
        /// </summary>
        internal static string FoodDetail_TotalSugars {
            get {
                return ResourceManager.GetString("FoodDetail_TotalSugars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you can select the Food Groups you&apos;re interested in..
        /// </summary>
        internal static string Groups_HelpText1 {
            get {
                return ResourceManager.GetString("Groups_HelpText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you switch off a Food Group we won&apos;t include foods from that group when you are searching..
        /// </summary>
        internal static string Groups_HelpText2 {
            get {
                return ResourceManager.GetString("Groups_HelpText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Food Groups.
        /// </summary>
        internal static string Groups_Title {
            get {
                return ResourceManager.GetString("Groups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry we couldn&apos;t find any foods that match your search.
        /// </summary>
        internal static string Search_NoMatches {
            get {
                return ResourceManager.GetString("Search_NoMatches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string Search_Search {
            get {
                return ResourceManager.GetString("Search_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Search_Searching {
            get {
                return ResourceManager.GetString("Search_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search_Title {
            get {
                return ResourceManager.GetString("Search_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fructose warning level.
        /// </summary>
        internal static string Settings_FructoseWarningLevel {
            get {
                return ResourceManager.GetString("Settings_FructoseWarningLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a food contains more than this many grams per 100 we&apos;ll highlight it..
        /// </summary>
        internal static string Settings_FructoseWarningLevelHelpText {
            get {
                return ResourceManager.GetString("Settings_FructoseWarningLevelHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is enabled we&apos;ll include foods in the search results even if we don&apos;t know how much Fructose they contain..
        /// </summary>
        internal static string Settings_UnknownFructoseHelpText {
            get {
                return ResourceManager.GetString("Settings_UnknownFructoseHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include foods with unknown Fructose.
        /// </summary>
        internal static string Settings_UnknownFructoseText {
            get {
                return ResourceManager.GetString("Settings_UnknownFructoseText", resourceCulture);
            }
        }
    }
}
